package training.lab.springsoapws.empleado_ws;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.02.22 at 09:48:02 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for articleInfo complex type.
* 
* <p>El siguiente fragmento de esquema especifica el contenido esperado dentro de esta clase.
* 
* <pre>
* &lt;complexType name="articleInfo">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="empleadoId" type="{http://www.w3.org/2001/XMLSchema}long"/>
*         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="apellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="departamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "empleadoInfo", propOrder = {
 "empleadoId",
 "nombre",
 "apellido",
 "departamento"
})
public class EmpleadoInfo {

 protected long empleadoId;
 @XmlElement(required = true)
 protected String nombre;
 @XmlElement(required = true)
 protected String apellido;
 @XmlElement(required = true)
 protected String departamento;
	/**
	 * @return the empleadoId
	 */
	public long getEmpleadoId() {
		return empleadoId;
	}
	/**
	 * @param empleadoId the empleadoId to set
	 */
	public void setEmpleadoId(long empleadoId) {
		this.empleadoId = empleadoId;
	}
	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}
	/**
	 * @param nombre the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	/**
	 * @return the apellido
	 */
	public String getApellido() {
		return apellido;
	}
	/**
	 * @param apellido the apellido to set
	 */
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}
	/**
	 * @return the departamento
	 */
	public String getDepartamento() {
		return departamento;
	}
	/**
	 * @param departamento the departamento to set
	 */
	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

 

}
