package training.lab.springsoapws.empleado_ws;
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.02.22 at 09:48:02 PM EST 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>El siguiente fragmento de esquema especifica el contenido esperado dentro de esta clase.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="empleadoInfo" type="{http://training.lab/empleado-ws}empleadoInfo" maxOccurs="unbounded"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "empleadoInfo"
})
@XmlRootElement(name = "getAllEmpleadosResponse")
public class GetAllEmpleadosResponse {

 @XmlElement(required = true)
 protected List<EmpleadoInfo> empleadoInfo;

 /**
  * Gets the value of the articleInfo property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the articleInfo property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getArticleInfo().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link EmpleadoInfo }
  * 
  * 
  */
 public List<EmpleadoInfo> getEmpleadoInfo() {
     if (empleadoInfo == null) {
     	empleadoInfo = new ArrayList<EmpleadoInfo>();
     }
     return this.empleadoInfo;
 }

}

