package training.lab.springsoapws.empleado_ws;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.02.22 at 09:48:02 PM EST 
//

import javax.xml.bind.annotation.XmlRegistry;


/**
* Este objeto contiene mÃ©todos de Factory para cada
* Interfaz de contenido Java e interfaz de elementos Java
* generado en el paquete training.lab.empleado_ws.
* <p>Una ObjectFactory le permite programÃ¡ticamente
* construir nuevas instancias de la representaciÃ³n de Java
* para contenido XML. La representaciÃ³n Java de XML
* el contenido puede consistir en interfaces derivadas de esquemas
* y clases que representan el enlace del esquema
* definiciones de tipo, declaraciones de elementos y modelo
* grupos. Los mÃ©todos de fÃ¡brica para cada uno de estos son
* proporcionado en esta clase.
* 
*/
@XmlRegistry  //indicar que una clase Java contiene mÃ©todos estÃ¡ticos que se 
//utilizan para crear instancias de objetos que se enlazarÃ¡n con XML.
public class ObjectFactory {


 /**
  * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: training.lab.empleado_ws
  * 
  */
 public ObjectFactory() {
 }

 /**
  * Create an instance of {@link GetAllEmpleadosRequest }
  * 
  */
 public GetAllEmpleadosRequest createGetAllEmpleadosRequest() {
     return new GetAllEmpleadosRequest();
 }

 /**
  * Create an instance of {@link GetEmpleadoByIdResponse }
  * 
  */
 public GetEmpleadoByIdResponse createGetEmpleadoByIdResponse() {
     return new GetEmpleadoByIdResponse();
 }

 /**
  * Create an instance of {@link EmpleadoInfo }
  * 
  */
 public EmpleadoInfo createEmpleadoInfo() {
     return new EmpleadoInfo();
 }

 /**
  * Create an instance of {@link GetEmpleadoByIdRequest }
  * 
  */
 public GetEmpleadoByIdRequest createGetEmpleadoByIdRequest() {
     return new GetEmpleadoByIdRequest();
 }

 /**
  * Create an instance of {@link DeleteEmpleadoRequest }
  * 
  */
 public DeleteEmpleadoRequest createDeleteEmpleadoRequest() {
     return new DeleteEmpleadoRequest();
 }

 /**
  * Create an instance of {@link AddEmpleadoResponse }
  * 
  */
 public AddEmpleadoResponse createAddEmpleadoResponse() {
     return new AddEmpleadoResponse();
 }

 /**
  * Create an instance of {@link ServiceStatus }
  * 
  */
 public ServiceStatus createServiceStatus() {
     return new ServiceStatus();
 }

 /**
  * Create an instance of {@link AddEmpleadoRequest }
  * 
  */
 public AddEmpleadoRequest createAddEmpleadoRequest() {
     return new AddEmpleadoRequest();
 }

 /**
  * Create an instance of {@link UpdateEmpleadoResponse }
  * 
  */
 public UpdateEmpleadoResponse createUpdateEmpleadoResponse() {
     return new UpdateEmpleadoResponse();
 }

 /**
  * Create an instance of {@link DeleteEmpleadoResponse }
  * 
  */
 public DeleteEmpleadoResponse createDeleteEmpleadoResponse() {
     return new DeleteEmpleadoResponse();
 }

 /**
  * Create an instance of {@link GetAllEmpleadosResponse }
  * 
  */
 public GetAllEmpleadosResponse createGetAllEmpleadosResponse() {
     return new GetAllEmpleadosResponse();
 }

 /**
  * Create an instance of {@link UpdateEmpleadoRequest }
  * 
  */
 public UpdateEmpleadoRequest createUpdateEmpleadoRequest() {
     return new UpdateEmpleadoRequest();
 }

}
